a = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaço? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanúmerico? {}'.format(a.isalnum()))
print('Está em maiusculas? {}'.format(a.isupper()))
print('Está em minuscula? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
print('Tem caracter especial? {}'.format(a.isidentifier()))

